//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ChienVHShopOnline.Models;
using Microsoft.EntityFrameworkCore;

namespace ChienVHShopOnline.Contexts
{

    public partial class ChienVHShopDBEntities : DbContext
    {
        public ChienVHShopDBEntities(DbContextOptions options) : base(options)
        {
        }


        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<OrderDetail>()
                                .HasOne(od => od.Order)
                                .WithMany(o => o.OrderDetails)
                                .HasForeignKey(od => od.OrderID);
            modelBuilder.Entity<OrderDetail>()
                                .HasOne(od => od.Product)
                                .WithMany(o => o.OrderDetails)
                                .HasForeignKey(od => od.ProductID);

            modelBuilder.Entity<Product>()
                                .HasOne(p => p.Category)
                                .WithMany(c => c.Products)
                                .HasForeignKey(p => p.CategoryId);
            modelBuilder.Entity<Product>()
                                .HasOne(p => p.Color)
                                .WithMany(c => c.Products)
                                .HasForeignKey(p => p.ColorId);
            modelBuilder.Entity<Product>()
                                .HasOne(p => p.Model)
                                .WithMany(m => m.Products)
                                .HasForeignKey(p => p.ModelId);
            modelBuilder.Entity<Product>()
                                .HasOne(p => p.User)
                                .WithMany(u => u.Products)
                                .HasForeignKey(p => p.UserId);

            modelBuilder.Entity<News>()
                                .HasOne(p => p.User)
                                .WithMany(u => u.News)
                                .HasForeignKey(p => p.NewsId);

        }
    }
}
